# Generated by Django 3.1.14 on 2023-03-26 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ping', '0003_auto_20230324_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='pings',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
